### ISSUE TITLE
Add U3 support

### ISSUE THREAD

**Issue by eliasrg** [we-taper/qiskit-pyzx#2]
U3 gates don't seem to work. But, a U3 gate can be expanded as 3 rotations via its Euler angles, which you can find using `qiskit.quantum_info.synthesis.euler_angles_1q`. Either create a new pyZX gate and provide a rule to perform the decomposition (probably preferable), or decompose U3 gates before converting into the pyZX format.

**Comment by we-taper** [comment]
Solved
